import Header from './components/Header'
import './globals.css';

export const metadata = {
  title: 'Profile | Fahad Ibne Hossain',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[url('../resource/bg_5.png')] bg-cover bg-no-repeat min-h-screen bg-fixed">
        <Header />
        {children}
        
        </body>
    </html>
  )
}
